# Konfigurasi untuk multiple data sources
# Setiap item di bawah adalah satu sumber data yang akan di-scrape dan diupdate.

# Konfigurasi untuk multiple data sources dengan API

# Konfigurasi untuk multiple data sources dengan data di dalam script

# Konfigurasi untuk multiple data sources dengan data di HTML statis

- name: "SDP"
  url: "https://srv1.scanangka.blog/keluaranharian?pasaran=sydney"
  target_file: "datasdp"
  scraper_type: "static_table" 

- name: "SDL"
  url: "https://srv1.scanangka.blog/keluaranharian?pasaran=sydney%20lotto"
  target_file: "sdlot"
  scraper_type: "static_table"

- name: "SG"
  url: "https://srv1.scanangka.blog/keluaranharian?pasaran=singapore"
  target_file: "datasg"
  scraper_type: "static_table"

- name: "MQ18"
  url: "https://srv1.scanangka.blog/keluaranharian?pasaran=morocco%20quatro%2018:00"
  target_file: "mq18"
  scraper_type: "static_table"

- name: "PCSO"
  url: "https://srv1.scanangka.blog/keluaranharian?pasaran=pcso"
  target_file: "pcso"
  scraper_type: "static_table"

- name: "HK"
  url: "https://srv1.scanangka.blog/keluaranharian?pasaran=hongkong"
  target_file: "datahkp"
  scraper_type: "static_table"

- name: "HKL"
  url: "https://srv1.scanangka.blog/keluaranharian?pasaran=hongkong%20lotto"
  target_file: "hklot"
  scraper_type: "static_table"

- name: "mq21"
  url: "https://srv1.scanangka.blog/keluaranharian?pasaran=morocco%20quatro%2021:00"
  target_file: "mq21"
  scraper_type: "static_table"

- name: "mq00"
  url: "https://srv1.scanangka.blog/keluaranharian?pasaran=morocco%20quatro%2000:00"
  target_file: "mq00"
  scraper_type: "static_table"

- name: "SG-Sabtu"
  url: "https://srv1.scanangka.blog/keluaranmingguan?pasaran=singapore&hari=sabtu"
  target_file: "sgsab"
  scraper_type: "static_table" 

- name: "SG-Minggu"
  url: "https://srv1.scanangka.blog/keluaranmingguan?pasaran=singapore&hari=minggu"
  target_file: "sgmin"
  scraper_type: "static_table" 

- name: "SG-Rabu"
  url: "https://srv1.scanangka.blog/keluaranmingguan?pasaran=singapore&hari=rabu"
  target_file: "sgrab"
  scraper_type: "static_table" 

# Untuk menambah sumber baru, cukup tambahkan blok dengan scraper_type "scanangka_api"
# dan sesuaikan api_pasaran-nya.

# Untuk menambah sumber data baru, cukup salin salah satu blok di atas
# dan sesuaikan name, url, dan target_file.
# Contoh:
# - name: "SGP"
#   url: "https://example.com/result-sgp"
#   target_file: "datasgp"
#   scraper_type: "default"
