# Konfigurasi untuk multiple data sources
# Setiap item di bawah adalah satu sumber data yang akan di-scrape dan diupdate.

# Konfigurasi untuk multiple data sources dengan API

# Konfigurasi untuk multiple data sources dengan data di dalam script

- name: "SDP"
  url: "https://srv1.scanangka.blog/keluaranharian?pasaran=sydney"
  target_file: "datasdp"
  scraper_type: "embedded_script" # Tipe scraper baru
  search_keyword: "sydney" # Kata kunci unik untuk menemukan script yang benar

- name: "HK"
  url: "https://srv1.scanangka.blog/keluaranharian?pasaran=hongkong"
  target_file: "datahkp"
  scraper_type: "embedded_script"
  search_keyword: "hongkong"

# Untuk menambah sumber baru, cukup tambahkan blok dengan scraper_type "scanangka_api"
# dan sesuaikan api_pasaran-nya.

# Untuk menambah sumber data baru, cukup salin salah satu blok di atas
# dan sesuaikan name, url, dan target_file.
# Contoh:
# - name: "SGP"
#   url: "https://example.com/result-sgp"
#   target_file: "datasgp"
#   scraper_type: "default"
