# Nama workflow yang akan tampil di tab Actions
name: Daily Data Update

# Menentukan kapan workflow ini akan dijalankan
on:
  # Schedule: menjalankan berdasarkan waktu (cron job)
  # '0 2 * * *' berarti setiap hari pada pukul 02:00 UTC.
  # Anda bisa mengatur waktunya. Gunakan https://crontab.guru untuk membantu.
  schedule:
    - cron: '0 8 * * *' 
  
  # Workflow Dispatch: memungkinkan menjalankan secara manual dari halaman GitHub
  workflow_dispatch:

# Pekerjaan yang akan dijalankan
jobs:
  build:
    # Menjalankan pada environment Ubuntu terbaru
    runs-on: ubuntu-latest

    # Langkah-langkah yang akan dilakukan
    steps:
      # Langkah 1: Checkout kode dari repositori
      - name: Checkout repository
        uses: actions/checkout@v3

      # Langkah 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Gunakan versi Python yang Anda inginkan

      # Langkah 3: Install library dari requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Langkah 4: Jalankan skrip Python
      - name: Run scraping script
        env:
          # Meneruskan secret 'GH_PAT' ke environment variabel skrip
          GH_PAT: ${{ secrets.GH_PAT }}
        run: python update_data.py
